# Generated by Django 5.1.6 on 2025-02-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='empleados',
            new_name='empleado',
        ),
    ]
