# Generated by Django 5.1.6 on 2025-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_options_empleado_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contadorew'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otros')], max_length=2, verbose_name='Cargo'),
        ),
    ]
