# Generated by Django 5.1.6 on 2025-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prueba',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
