# Generated by Django 5.1.6 on 2025-02-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad_alter_prueba_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
