# Generated by Django 5.1.6 on 2025-02-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_prueba_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['id']},
        ),
    ]
